name= input()
id= input()
x=Chinese_score=input()
y=Introduction_of_Computer_Science_score=input()
z=Computer_programming_score=input()
print("Name:"+name)
print("Id:"+id)
print("Total:",int(x)+int(y)+int(z),sep='')
print("Average:",(int(x)+int(y)+int(z))//3,sep='')
